---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'foundation'
  #rewrite_hash_links: false
NewsAdmin:
  extensions:
    - SubsiteMenuExtension
News:
  api_access: true
  default_sort: "\"PublishFrom\" DESC, \"ID\" DESC"
  extensions:
    - BlizzgameNewsExtension
DataObject:
  extensions:
    - BlizzgameObjectExtension
Image:
  api_access: true
ElementLink:
  api_access: true
StormHero:
  api_access: true
GalleryImage:
  #api_access: true
  extensions:
    - ObjectAsPageExtension
CardGameItem:
  #api_access: true
  extensions:
    - ObjectAsPageExtension
Book:
  api_access: true
  extensions:
    - ObjectAsPageExtension
Chapter:
  api_access: true
  extensions:
    - ObjectAsPageExtension
PeopleFace:
  api_access: true
  extensions:
    - ObjectAsPageExtension
ChronicleItem:
  api_access: true
  extensions:
    - ObjectAsPageExtension
Media:
  api_access: true
  extensions:
    - ObjectAsPageExtension
SiteTree:
  extensions:
    - BlizzgamePageExtension
Page:
  api_access: true
SiteConfig:
  extensions:
    - BlizzgameConfigExtension
