---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'foundation'
NewsAdmin:
  extensions:
    - SubsiteMenuExtension
Member:
  extensions:
    - BnetMemberExtension
DataObject:
  extensions:
    - BlizzgameObjectExtension
GalleryImage:
  extensions:
    - ObjectAsPageExtension
Book:
  extensions:
    - ObjectAsPageExtension
Chapter:
  extensions:
    - ObjectAsPageExtension
PeopleFace:
  extensions:
    - ObjectAsPageExtension
ChronicleItem:
  extensions:
    - ObjectAsPageExtension
SiteTree:
  extensions:
    - BlizzgamePageExtension
SiteConfig:
  extensions:
    ['BlizzgameConfigExtension']